services: # Docker compose expects a services 
  backend: # Name of the service
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    environment:
      - PORT=8000
      - MY_PROJECT=Hello World 
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt 
        - action: rebuild
          path: backend/Dockerfile 
        - action: restart
          path: backend/src/
          #target: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: frontend/requirements.txt
        - action: rebuild
          path: frontend/Dockerfile
        - action: sync+restart
          path: frontend/
          target: /app

# Database_URL=postgresql+psycopg://dbuser:db-password@db_service:5432/mydb
  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    volumes:
      - dc_manage_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb

volumes:
  dc_manage_db_data:
